/**
 * ShipmentEvent — the single canonical schema owned by Control Tower.
 * Every adapter normalises its source data into this shape before
 * calling POST /api/ingest. The disruption engine, alert router,
 * dashboard, and analytics only ever process ShipmentEvent objects.
 *
 * @typedef {Object} ShipmentEvent
 * @property {string}  eventId       - UUID, generated by adapter if absent
 * @property {string}  source        - identifies the originating system
 * @property {string}  sourceRef     - source-internal shipment / trip ID
 * @property {string}  occurredAt    - ISO 8601 timestamp
 * @property {Object}  shipment
 * @property {string}  shipment.id           - CT-scoped shipment ID (upserted on ingest)
 * @property {string}  shipment.reference    - human-readable reference number
 * @property {Object}  shipment.origin       - { name, lat, lng }
 * @property {Object}  shipment.destination  - { name, lat, lng }
 * @property {string}  shipment.slaDeadline  - ISO 8601
 * @property {Object}  shipment.transporter  - { id, name }
 * @property {Object}  shipment.vehicle      - { id, regNo }
 * @property {Object}  status
 * @property {string}  status.code     - IN_TRANSIT | HALTED | DELAYED | DELIVERED | EXCEPTION
 * @property {Object}  status.location - { lat, lng }
 * @property {string}  status.eta      - ISO 8601
 * @property {number}  status.odometer
 * @property {string}  status.message  - optional human-readable note
 * @property {Object}  meta            - free-form source-specific data (passed through, never evaluated)
 */

export function validateShipmentEvent(event) {
  const errors = [];
  if (!event.eventId)            errors.push('eventId is required');
  if (!event.source)             errors.push('source is required');
  if (!event.occurredAt)         errors.push('occurredAt is required');
  if (!event.shipment)           errors.push('shipment object is required');
  if (!event.shipment?.reference)errors.push('shipment.reference is required');
  if (!event.status)             errors.push('status object is required');
  if (!event.status?.code)       errors.push('status.code is required');

  const validCodes = ['IN_TRANSIT','HALTED','DELAYED','DELIVERED','EXCEPTION'];
  if (event.status?.code && !validCodes.includes(event.status.code)) {
    errors.push(`status.code must be one of: ${validCodes.join(', ')}`);
  }
  return errors;
}

export const EXAMPLE_EVENT = {
  eventId:    '550e8400-e29b-41d4-a716-446655440000',
  source:     'haulsync-ftl',
  sourceRef:  'TRIP-12345',
  occurredAt: new Date().toISOString(),
  shipment: {
    id:          null,
    reference:   'HS/2024/8821',
    origin:      { name: 'Mumbai', lat: 19.076, lng: 72.877 },
    destination: { name: 'Delhi',  lat: 28.613, lng: 77.209 },
    slaDeadline: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    transporter: { id: null, name: 'FastFreight Co' },
    vehicle:     { id: null, regNo: 'MH-04-AB-1234' },
  },
  status: {
    code:     'IN_TRANSIT',
    location: { lat: 21.146, lng: 79.088 },
    eta:      new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    odometer: 412.5,
    message:  null,
  },
  meta: {},
};
